//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhistleblowerSystem.Client.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App_de {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App_de() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WhistleblowerSystem.Client.Resources.App_de", typeof(App_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string index_contact {
            get {
                return ResourceManager.GetString("index_contact", resourceCulture);
            }
        }
        
        public static string index_info_text_1 {
            get {
                return ResourceManager.GetString("index_info_text_1", resourceCulture);
            }
        }
        
        public static string index_info_text_2 {
            get {
                return ResourceManager.GetString("index_info_text_2", resourceCulture);
            }
        }
        
        public static string index_info_text_3 {
            get {
                return ResourceManager.GetString("index_info_text_3", resourceCulture);
            }
        }
        
        public static string index_info_text_4 {
            get {
                return ResourceManager.GetString("index_info_text_4", resourceCulture);
            }
        }
        
        public static string index_info_text_5 {
            get {
                return ResourceManager.GetString("index_info_text_5", resourceCulture);
            }
        }
        
        public static string index_info_text_6 {
            get {
                return ResourceManager.GetString("index_info_text_6", resourceCulture);
            }
        }
        
        public static string index_info_text_7 {
            get {
                return ResourceManager.GetString("index_info_text_7", resourceCulture);
            }
        }
        
        public static string manual_title {
            get {
                return ResourceManager.GetString("manual_title", resourceCulture);
            }
        }
        
        public static string faq_title {
            get {
                return ResourceManager.GetString("faq_title", resourceCulture);
            }
        }
        
        public static string securitynotice_title {
            get {
                return ResourceManager.GetString("securitynotice_title", resourceCulture);
            }
        }
        
        public static string securitynotice_subtitle {
            get {
                return ResourceManager.GetString("securitynotice_subtitle", resourceCulture);
            }
        }
        
        public static string securitynotice_list_title {
            get {
                return ResourceManager.GetString("securitynotice_list_title", resourceCulture);
            }
        }
        
        public static string securitynotice_list_item_1 {
            get {
                return ResourceManager.GetString("securitynotice_list_item_1", resourceCulture);
            }
        }
        
        public static string securitynotice_list_item_2 {
            get {
                return ResourceManager.GetString("securitynotice_list_item_2", resourceCulture);
            }
        }
        
        public static string securitynotice_list_item_3 {
            get {
                return ResourceManager.GetString("securitynotice_list_item_3", resourceCulture);
            }
        }
        
        public static string securitynotice_list_item_4 {
            get {
                return ResourceManager.GetString("securitynotice_list_item_4", resourceCulture);
            }
        }
        
        public static string securitynotice_checkbox_title {
            get {
                return ResourceManager.GetString("securitynotice_checkbox_title", resourceCulture);
            }
        }
        
        public static string securitynotice_checkbox_text {
            get {
                return ResourceManager.GetString("securitynotice_checkbox_text", resourceCulture);
            }
        }
        
        public static string securitynotice_continue {
            get {
                return ResourceManager.GetString("securitynotice_continue", resourceCulture);
            }
        }
        
        public static string newreport_title {
            get {
                return ResourceManager.GetString("newreport_title", resourceCulture);
            }
        }
        
        public static string newreport_continue {
            get {
                return ResourceManager.GetString("newreport_continue", resourceCulture);
            }
        }
        
        public static string newreport_placeholder_text {
            get {
                return ResourceManager.GetString("newreport_placeholder_text", resourceCulture);
            }
        }
        
        public static string newreport_placeholder_select {
            get {
                return ResourceManager.GetString("newreport_placeholder_select", resourceCulture);
            }
        }
        
        public static string login_title {
            get {
                return ResourceManager.GetString("login_title", resourceCulture);
            }
        }
        
        public static string login_password {
            get {
                return ResourceManager.GetString("login_password", resourceCulture);
            }
        }
        
        public static string login_email {
            get {
                return ResourceManager.GetString("login_email", resourceCulture);
            }
        }
        
        public static string login_continue {
            get {
                return ResourceManager.GetString("login_continue", resourceCulture);
            }
        }
        
        public static string upload_title {
            get {
                return ResourceManager.GetString("upload_title", resourceCulture);
            }
        }
        
        public static string upload_text_1 {
            get {
                return ResourceManager.GetString("upload_text_1", resourceCulture);
            }
        }
        
        public static string upload_text_2 {
            get {
                return ResourceManager.GetString("upload_text_2", resourceCulture);
            }
        }
        
        public static string upload_thanks {
            get {
                return ResourceManager.GetString("upload_thanks", resourceCulture);
            }
        }
        
        public static string upload_back {
            get {
                return ResourceManager.GetString("upload_back", resourceCulture);
            }
        }
        
        public static string upload_continue {
            get {
                return ResourceManager.GetString("upload_continue", resourceCulture);
            }
        }
        
        public static string upload_hint {
            get {
                return ResourceManager.GetString("upload_hint", resourceCulture);
            }
        }
        
        public static string confirmation_title {
            get {
                return ResourceManager.GetString("confirmation_title", resourceCulture);
            }
        }
        
        public static string confirmation_subtitle {
            get {
                return ResourceManager.GetString("confirmation_subtitle", resourceCulture);
            }
        }
        
        public static string confirmation_caseid {
            get {
                return ResourceManager.GetString("confirmation_caseid", resourceCulture);
            }
        }
        
        public static string confirmation_text {
            get {
                return ResourceManager.GetString("confirmation_text", resourceCulture);
            }
        }
        
        public static string confirmation_password {
            get {
                return ResourceManager.GetString("confirmation_password", resourceCulture);
            }
        }
        
        public static string confirmation_continue {
            get {
                return ResourceManager.GetString("confirmation_continue", resourceCulture);
            }
        }
        
        public static string viewreports_title {
            get {
                return ResourceManager.GetString("viewreports_title", resourceCulture);
            }
        }
        
        public static string viewreports_text {
            get {
                return ResourceManager.GetString("viewreports_text", resourceCulture);
            }
        }
        
        public static string viewreports_password {
            get {
                return ResourceManager.GetString("viewreports_password", resourceCulture);
            }
        }
        
        public static string viewreports_continue {
            get {
                return ResourceManager.GetString("viewreports_continue", resourceCulture);
            }
        }
        
        public static string viewreports_id {
            get {
                return ResourceManager.GetString("viewreports_id", resourceCulture);
            }
        }
        
        public static string faq_question_1 {
            get {
                return ResourceManager.GetString("faq_question_1", resourceCulture);
            }
        }
        
        public static string faq_question_2 {
            get {
                return ResourceManager.GetString("faq_question_2", resourceCulture);
            }
        }
        
        public static string faq_question_3 {
            get {
                return ResourceManager.GetString("faq_question_3", resourceCulture);
            }
        }
        
        public static string faq_question_4 {
            get {
                return ResourceManager.GetString("faq_question_4", resourceCulture);
            }
        }
        
        public static string faq_question_5 {
            get {
                return ResourceManager.GetString("faq_question_5", resourceCulture);
            }
        }
        
        public static string faq_question_6 {
            get {
                return ResourceManager.GetString("faq_question_6", resourceCulture);
            }
        }
        
        public static string faq_question_7 {
            get {
                return ResourceManager.GetString("faq_question_7", resourceCulture);
            }
        }
        
        public static string faq_answer_1 {
            get {
                return ResourceManager.GetString("faq_answer_1", resourceCulture);
            }
        }
        
        public static string faq_answer_2 {
            get {
                return ResourceManager.GetString("faq_answer_2", resourceCulture);
            }
        }
        
        public static string faq_answer_3 {
            get {
                return ResourceManager.GetString("faq_answer_3", resourceCulture);
            }
        }
        
        public static string faq_answer_4 {
            get {
                return ResourceManager.GetString("faq_answer_4", resourceCulture);
            }
        }
        
        public static string faq_answer_5 {
            get {
                return ResourceManager.GetString("faq_answer_5", resourceCulture);
            }
        }
        
        public static string faq_answer_6 {
            get {
                return ResourceManager.GetString("faq_answer_6", resourceCulture);
            }
        }
        
        public static string faq_answer_7 {
            get {
                return ResourceManager.GetString("faq_answer_7", resourceCulture);
            }
        }
        
        public static string faq_subtitle_1 {
            get {
                return ResourceManager.GetString("faq_subtitle_1", resourceCulture);
            }
        }
        
        public static string faq_subtitle_2 {
            get {
                return ResourceManager.GetString("faq_subtitle_2", resourceCulture);
            }
        }
        
        public static string faq_subtitle_3 {
            get {
                return ResourceManager.GetString("faq_subtitle_3", resourceCulture);
            }
        }
        
        public static string reportslist_table_caseid {
            get {
                return ResourceManager.GetString("reportslist_table_caseid", resourceCulture);
            }
        }
        
        public static string reportslist_table_date {
            get {
                return ResourceManager.GetString("reportslist_table_date", resourceCulture);
            }
        }
        
        public static string reportslist_table_search {
            get {
                return ResourceManager.GetString("reportslist_table_search", resourceCulture);
            }
        }
        
        public static string reportslist_table_state {
            get {
                return ResourceManager.GetString("reportslist_table_state", resourceCulture);
            }
        }
        
        public static string reportslist_table_subject {
            get {
                return ResourceManager.GetString("reportslist_table_subject", resourceCulture);
            }
        }
        
        public static string reportslist_title {
            get {
                return ResourceManager.GetString("reportslist_title", resourceCulture);
            }
        }
        
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        public static string reportdetailview_title {
            get {
                return ResourceManager.GetString("reportdetailview_title", resourceCulture);
            }
        }
        
        public static string reportdetailview_report {
            get {
                return ResourceManager.GetString("reportdetailview_report", resourceCulture);
            }
        }
        
        public static string reportdetailview_additionalinfo {
            get {
                return ResourceManager.GetString("reportdetailview_additionalinfo", resourceCulture);
            }
        }
        
        public static string reportdetailview_entermessage {
            get {
                return ResourceManager.GetString("reportdetailview_entermessage", resourceCulture);
            }
        }
        
        public static string reportdetailview_nomessages {
            get {
                return ResourceManager.GetString("reportdetailview_nomessages", resourceCulture);
            }
        }
        
        public static string reportdetailview_send {
            get {
                return ResourceManager.GetString("reportdetailview_send", resourceCulture);
            }
        }
        
        public static string reportdetailview_close {
            get {
                return ResourceManager.GetString("reportdetailview_close", resourceCulture);
            }
        }
        
        public static string reportdetailview_savestate {
            get {
                return ResourceManager.GetString("reportdetailview_savestate", resourceCulture);
            }
        }
        
        public static string reportdetailview_state {
            get {
                return ResourceManager.GetString("reportdetailview_state", resourceCulture);
            }
        }
        
        public static string reportdetailview_messages {
            get {
                return ResourceManager.GetString("reportdetailview_messages", resourceCulture);
            }
        }
        
        public static string reportdetailview_sender_you {
            get {
                return ResourceManager.GetString("reportdetailview_sender_you", resourceCulture);
            }
        }
        
        public static string reportdetailview_sender_clerk {
            get {
                return ResourceManager.GetString("reportdetailview_sender_clerk", resourceCulture);
            }
        }
        
        public static string reportdetailview_sender_reporter {
            get {
                return ResourceManager.GetString("reportdetailview_sender_reporter", resourceCulture);
            }
        }
        
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        public static string reportdetailview_description {
            get {
                return ResourceManager.GetString("reportdetailview_description", resourceCulture);
            }
        }
        
        public static string reportdetailview_add_documents {
            get {
                return ResourceManager.GetString("reportdetailview_add_documents", resourceCulture);
            }
        }
        
        public static string reportdetailview_documents {
            get {
                return ResourceManager.GetString("reportdetailview_documents", resourceCulture);
            }
        }
        
        public static string whistleblowing_title {
            get {
                return ResourceManager.GetString("whistleblowing_title", resourceCulture);
            }
        }
        
        public static string newreport_required_error {
            get {
                return ResourceManager.GetString("newreport_required_error", resourceCulture);
            }
        }
        
        public static string reportdetailview_upload_warning {
            get {
                return ResourceManager.GetString("reportdetailview_upload_warning", resourceCulture);
            }
        }
        
        public static string reportdetailview_upload_warning_close {
            get {
                return ResourceManager.GetString("reportdetailview_upload_warning_close", resourceCulture);
            }
        }
        
        public static string reportdetailview_upload_warning_text {
            get {
                return ResourceManager.GetString("reportdetailview_upload_warning_text", resourceCulture);
            }
        }
        
        public static string disclaimer_infotext {
            get {
                return ResourceManager.GetString("disclaimer_infotext", resourceCulture);
            }
        }
        
        public static string disclaimer_whistleblower_contact {
            get {
                return ResourceManager.GetString("disclaimer_whistleblower_contact", resourceCulture);
            }
        }
        
        public static string disclaimer_mr {
            get {
                return ResourceManager.GetString("disclaimer_mr", resourceCulture);
            }
        }
        
        public static string disclaimer_project_contact {
            get {
                return ResourceManager.GetString("disclaimer_project_contact", resourceCulture);
            }
        }
        
        public static string show_reports {
            get {
                return ResourceManager.GetString("show_reports", resourceCulture);
            }
        }
        
        public static string already_logged_in {
            get {
                return ResourceManager.GetString("already_logged_in", resourceCulture);
            }
        }
        
        public static string viewreports_login_error {
            get {
                return ResourceManager.GetString("viewreports_login_error", resourceCulture);
            }
        }
    }
}
