//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhistleblowerSystem.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhistleblowerSystem.Client.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closed ähnelt.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your CaseID is:  ähnelt.
        /// </summary>
        public static string confirmation_caseid {
            get {
                return ResourceManager.GetString("confirmation_caseid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string confirmation_continue {
            get {
                return ResourceManager.GetString("confirmation_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Password is:  ähnelt.
        /// </summary>
        public static string confirmation_password {
            get {
                return ResourceManager.GetString("confirmation_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you for your report! ähnelt.
        /// </summary>
        public static string confirmation_subtitle {
            get {
                return ResourceManager.GetString("confirmation_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die With the CaseID and your password you can view the status of your report at any time under &quot;View report&quot;. Please make a note of the CaseID and password immediately. As soon as you close this window, the CaseID and the password can no longer be accessed or changed. ähnelt.
        /// </summary>
        public static string confirmation_text {
            get {
                return ResourceManager.GetString("confirmation_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Completion ähnelt.
        /// </summary>
        public static string confirmation_title {
            get {
                return ResourceManager.GetString("confirmation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A whistleblower is a person, who has knowledge of wrongdoing within an organization and discloses this information. The wrongdoing may relate to legal violations or unethical behavior. 
        ///Whistleblowers typically disclose this information by name or anonymously. 
        /// ähnelt.
        /// </summary>
        public static string faq_answer_1 {
            get {
                return ResourceManager.GetString("faq_answer_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The EU Whistleblower Protection Policy 2019/1937 is an EU guideline that came into force in 2019 through development by the EU Commission and adoption by the EU Council.
        ///Its purpose is to protect whistleblowers, who point out wrongdoings in an organization. 
        ///All organizations with 50 or more employees are required to establish a whistleblower system in their organization. For organizations with 250 or more employees, the expected implementation period is 2 years. For organizations between 50 and 249 emplo [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string faq_answer_2 {
            get {
                return ResourceManager.GetString("faq_answer_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die According to the EU Whistleblowing Guideline, the whistleblower must receive confirmation that his report has been received within seven days. After a further three months at latest, the reporting person must be informed of the status of the its report, what actions have been taken and what the results of these actions are. ähnelt.
        /// </summary>
        public static string faq_answer_3 {
            get {
                return ResourceManager.GetString("faq_answer_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Whistle-Blower Policy supports reporting against any compliance violations, such as bribery, corruption, privacy, discrimination, harassment, embezzlement, theft, health, safety, environmental, money laundering. ähnelt.
        /// </summary>
        public static string faq_answer_4 {
            get {
                return ResourceManager.GetString("faq_answer_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Whistleblowing is important to promote high ethical standards and thus maintain the trust of employees and the public in an organization. By reporting, you can help prevent a possible escalation of misconduct. ähnelt.
        /// </summary>
        public static string faq_answer_5 {
            get {
                return ResourceManager.GetString("faq_answer_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To enable a thorough investigation of your report, you should describe your case in detail (what exactly happened and when and where it happened). Additionally, you can upload documents and images as evidence for your report via our website. ähnelt.
        /// </summary>
        public static string faq_answer_6 {
            get {
                return ResourceManager.GetString("faq_answer_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The website is based on an independent service that establishes anonymous communication between you and the people who receive the report. Our service is separate from the organization&apos;s IT environment. We do not track IP addresses or other data that could identify an individual. Messages can only be decrypted and handled by specific individuals. Your sent metadata is not stored.
        ///Advice: We recommend that you access our website from a device that is not connected to the organization&apos;s IT environment.
        /// ähnelt.
        /// </summary>
        public static string faq_answer_7 {
            get {
                return ResourceManager.GetString("faq_answer_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What is a whistleblower? ähnelt.
        /// </summary>
        public static string faq_question_1 {
            get {
                return ResourceManager.GetString("faq_question_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What is the EU-Whistleblower Policy and who does it impact? ähnelt.
        /// </summary>
        public static string faq_question_2 {
            get {
                return ResourceManager.GetString("faq_question_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What are the deadlines for processing the report? ähnelt.
        /// </summary>
        public static string faq_question_3 {
            get {
                return ResourceManager.GetString("faq_question_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For which specific cases/misconducts is the whistleblower policy intended? ähnelt.
        /// </summary>
        public static string faq_question_4 {
            get {
                return ResourceManager.GetString("faq_question_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Why should a wrongdoing be reported? ähnelt.
        /// </summary>
        public static string faq_question_5 {
            get {
                return ResourceManager.GetString("faq_question_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What information do I need to create a report? ähnelt.
        /// </summary>
        public static string faq_question_6 {
            get {
                return ResourceManager.GetString("faq_question_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How is the anonymity of whistleblowers maintained? ähnelt.
        /// </summary>
        public static string faq_question_7 {
            get {
                return ResourceManager.GetString("faq_question_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What does whistleblowing mean? ähnelt.
        /// </summary>
        public static string faq_subtitle_1 {
            get {
                return ResourceManager.GetString("faq_subtitle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What topics does whistleblowing cover and why should I report them? ähnelt.
        /// </summary>
        public static string faq_subtitle_2 {
            get {
                return ResourceManager.GetString("faq_subtitle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How is the Security of my data or information assured? ähnelt.
        /// </summary>
        public static string faq_subtitle_3 {
            get {
                return ResourceManager.GetString("faq_subtitle_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FAQs ähnelt.
        /// </summary>
        public static string faq_title {
            get {
                return ResourceManager.GetString("faq_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact:  ähnelt.
        /// </summary>
        public static string index_contact {
            get {
                return ResourceManager.GetString("index_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trust and credibility play a central role for the FHNW. For this reason, the FHNW as well as its employees always aim for complete compliance with the law. Nevertheless, violations of the law in individual cases cannot be completely ruled out. ähnelt.
        /// </summary>
        public static string index_info_text_1 {
            get {
                return ResourceManager.GetString("index_info_text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you have a hint of irregularities, acts of corruption or other illegal activities? We offer you the opportunity to report suspected misconduct on this website. ähnelt.
        /// </summary>
        public static string index_info_text_2 {
            get {
                return ResourceManager.GetString("index_info_text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This web-based reporting site ensures anonymity and protected handling of the data received. The report can be submitted either completely anonymously or by providing your name. Neither the technical team nor the support team of the website will be able to identify you in any way.  ähnelt.
        /// </summary>
        public static string index_info_text_3 {
            get {
                return ResourceManager.GetString("index_info_text_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In addition, after submitting your report, you will have the opportunity to interact anonymously with our professionals. All information and conversations will be kept confidential.  ähnelt.
        /// </summary>
        public static string index_info_text_4 {
            get {
                return ResourceManager.GetString("index_info_text_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please ensure that you do not use the infrastructure provided by your organization (such as PC, tablet, mobile device) when submitting anonymous reports. To submit a report, read the FAQs and instructions carefully to ensure the greatest possible protection of your identity. ähnelt.
        /// </summary>
        public static string index_info_text_5 {
            get {
                return ResourceManager.GetString("index_info_text_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All further details on the use of the reporting system can be found in the instructions. If you have any questions about reporting, please refer to the FAQs.  ähnelt.
        /// </summary>
        public static string index_info_text_6 {
            get {
                return ResourceManager.GetString("index_info_text_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you for submitting such important information! Only if we have this information, we can take actions. ähnelt.
        /// </summary>
        public static string index_info_text_7 {
            get {
                return ResourceManager.GetString("index_info_text_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string login_continue {
            get {
                return ResourceManager.GetString("login_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-mail ähnelt.
        /// </summary>
        public static string login_email {
            get {
                return ResourceManager.GetString("login_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string login_password {
            get {
                return ResourceManager.GetString("login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login reciever ähnelt.
        /// </summary>
        public static string login_title {
            get {
                return ResourceManager.GetString("login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual ähnelt.
        /// </summary>
        public static string manual_title {
            get {
                return ResourceManager.GetString("manual_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue ähnelt.
        /// </summary>
        public static string newreport_continue {
            get {
                return ResourceManager.GetString("newreport_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select ähnelt.
        /// </summary>
        public static string newreport_placeholder_select {
            get {
                return ResourceManager.GetString("newreport_placeholder_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter text... ähnelt.
        /// </summary>
        public static string newreport_placeholder_text {
            get {
                return ResourceManager.GetString("newreport_placeholder_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Describe report ähnelt.
        /// </summary>
        public static string newreport_title {
            get {
                return ResourceManager.GetString("newreport_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In progress ähnelt.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Received ähnelt.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload additional documents ähnelt.
        /// </summary>
        public static string reportdetailview_add_documents {
            get {
                return ResourceManager.GetString("reportdetailview_add_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additional information:  ähnelt.
        /// </summary>
        public static string reportdetailview_additionalinfo {
            get {
                return ResourceManager.GetString("reportdetailview_additionalinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close report ähnelt.
        /// </summary>
        public static string reportdetailview_close {
            get {
                return ResourceManager.GetString("reportdetailview_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string reportdetailview_description {
            get {
                return ResourceManager.GetString("reportdetailview_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Documents: ähnelt.
        /// </summary>
        public static string reportdetailview_documents {
            get {
                return ResourceManager.GetString("reportdetailview_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter new message ähnelt.
        /// </summary>
        public static string reportdetailview_entermessage {
            get {
                return ResourceManager.GetString("reportdetailview_entermessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messages ähnelt.
        /// </summary>
        public static string reportdetailview_messages {
            get {
                return ResourceManager.GetString("reportdetailview_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No messages sent yet ähnelt.
        /// </summary>
        public static string reportdetailview_nomessages {
            get {
                return ResourceManager.GetString("reportdetailview_nomessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report:  ähnelt.
        /// </summary>
        public static string reportdetailview_report {
            get {
                return ResourceManager.GetString("reportdetailview_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save state ähnelt.
        /// </summary>
        public static string reportdetailview_savestate {
            get {
                return ResourceManager.GetString("reportdetailview_savestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die send ähnelt.
        /// </summary>
        public static string reportdetailview_send {
            get {
                return ResourceManager.GetString("reportdetailview_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clerk ähnelt.
        /// </summary>
        public static string reportdetailview_sender_clerk {
            get {
                return ResourceManager.GetString("reportdetailview_sender_clerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reporter ähnelt.
        /// </summary>
        public static string reportdetailview_sender_reporter {
            get {
                return ResourceManager.GetString("reportdetailview_sender_reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You ähnelt.
        /// </summary>
        public static string reportdetailview_sender_you {
            get {
                return ResourceManager.GetString("reportdetailview_sender_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die State: ähnelt.
        /// </summary>
        public static string reportdetailview_state {
            get {
                return ResourceManager.GetString("reportdetailview_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Case: ähnelt.
        /// </summary>
        public static string reportdetailview_title {
            get {
                return ResourceManager.GetString("reportdetailview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CaseID ähnelt.
        /// </summary>
        public static string reportslist_table_caseid {
            get {
                return ResourceManager.GetString("reportslist_table_caseid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string reportslist_table_date {
            get {
                return ResourceManager.GetString("reportslist_table_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search By CaseID ähnelt.
        /// </summary>
        public static string reportslist_table_search {
            get {
                return ResourceManager.GetString("reportslist_table_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string reportslist_table_state {
            get {
                return ResourceManager.GetString("reportslist_table_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subject ähnelt.
        /// </summary>
        public static string reportslist_table_subject {
            get {
                return ResourceManager.GetString("reportslist_table_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reports ähnelt.
        /// </summary>
        public static string reportslist_title {
            get {
                return ResourceManager.GetString("reportslist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To enter your report, you must agree to these security notice. ähnelt.
        /// </summary>
        public static string securitynotice_checkbox_text {
            get {
                return ResourceManager.GetString("securitynotice_checkbox_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To enter your report, you must agree to these security notice. ähnelt.
        /// </summary>
        public static string securitynotice_checkbox_title {
            get {
                return ResourceManager.GetString("securitynotice_checkbox_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue ähnelt.
        /// </summary>
        public static string securitynotice_continue {
            get {
                return ResourceManager.GetString("securitynotice_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Our website is separate from our organization&apos;s IT environment ähnelt.
        /// </summary>
        public static string securitynotice_list_item_1 {
            get {
                return ResourceManager.GetString("securitynotice_list_item_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you wish to remain anonymous, do not include any personal information in your report. Avoid data that could be used to identify you individually ähnelt.
        /// </summary>
        public static string securitynotice_list_item_2 {
            get {
                return ResourceManager.GetString("securitynotice_list_item_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do not use a device provided by your organization to report your case ähnelt.
        /// </summary>
        public static string securitynotice_list_item_3 {
            get {
                return ResourceManager.GetString("securitynotice_list_item_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We ensure that reporting metadata is not stored in any way ähnelt.
        /// </summary>
        public static string securitynotice_list_item_4 {
            get {
                return ResourceManager.GetString("securitynotice_list_item_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To further enhance your security, please note the following points: ähnelt.
        /// </summary>
        public static string securitynotice_list_title {
            get {
                return ResourceManager.GetString("securitynotice_list_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Our reporting system provides technical protection for your identity and the content you submit.  ähnelt.
        /// </summary>
        public static string securitynotice_subtitle {
            get {
                return ResourceManager.GetString("securitynotice_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Security notice ähnelt.
        /// </summary>
        public static string securitynotice_title {
            get {
                return ResourceManager.GetString("securitynotice_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back  ähnelt.
        /// </summary>
        public static string upload_back {
            get {
                return ResourceManager.GetString("upload_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send ähnelt.
        /// </summary>
        public static string upload_continue {
            get {
                return ResourceManager.GetString("upload_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag and drop your documents here or click ähnelt.
        /// </summary>
        public static string upload_hint {
            get {
                return ResourceManager.GetString("upload_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Evidence is important to accurately understand and analyse the situation in your report. If you would like to upload relevant data, please use the upload section below. This will help us to process your case more effectively and efficiently. ähnelt.
        /// </summary>
        public static string upload_text_1 {
            get {
                return ResourceManager.GetString("upload_text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Note about sending attachments: Files may contain hidden personal data that may compromise your anonymity. Please remove this data before sending. ähnelt.
        /// </summary>
        public static string upload_text_2 {
            get {
                return ResourceManager.GetString("upload_text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you for your cooperation! ähnelt.
        /// </summary>
        public static string upload_thanks {
            get {
                return ResourceManager.GetString("upload_thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload documents ähnelt.
        /// </summary>
        public static string upload_title {
            get {
                return ResourceManager.GetString("upload_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        public static string viewreports_continue {
            get {
                return ResourceManager.GetString("viewreports_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CaseId ähnelt.
        /// </summary>
        public static string viewreports_id {
            get {
                return ResourceManager.GetString("viewreports_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string viewreports_password {
            get {
                return ResourceManager.GetString("viewreports_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your CaseID and your password: ähnelt.
        /// </summary>
        public static string viewreports_text {
            get {
                return ResourceManager.GetString("viewreports_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View report ähnelt.
        /// </summary>
        public static string viewreports_title {
            get {
                return ResourceManager.GetString("viewreports_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We offer you the opportunity to submit whistleblowing reports via this channel, even anonymously if necessary ähnelt.
        /// </summary>
        public static string whistleblowing_title {
            get {
                return ResourceManager.GetString("whistleblowing_title", resourceCulture);
            }
        }
    }
}
